language: node_js
node_js:
  - "6"
  - "5"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
after_success:
  - "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
